### ISSUE TITLE
Sense of control in forms guidance

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#757] opened 2020-10-21 21:15 UTC
## What

This hasn't yet been covered in the questions guidance - along with service delivery. It was identified as an area which might need more work.

**Comment by cjforms** [comment] 2020-10-22 10:38
I'm really keen to see this topic covered in the guidance. It's been missing from all forms guidance for a long time. 

The GDS 'task list' pattern comes closest to providing a route to sense of control. I'd love to see that researched more, both with users and designers. My view is that it's basically OK, and I'd like to see research around these things:

- the content design of the instructions to users about how it works
- the indicator of status. I'm worried by a thing that looks a bit like a button but isn't a button
- the service design of the things that go into the task list, and how to show completed tasks, tasks that aren't done by the user, content-only tasks (such as 'read xxx'), declarations and where to put them, and tasks that happen after a delay caused by tasks that aren't done by the users.

**Comment by sarawilcox** [comment] 2022-01-10 14:25
I'm going to close this issue down but have noted @cjforms' comment on task lists on our task list component in the design system backlog. Hope that's OK, Caroline.

**Closed by sarawilcox** 2022-01-10 14:25 UTC
Labels: guidance, content style guide

**Comment by cjforms** [comment] 2022-01-10 14:43
I still think that this is a major issue that is missing from all forms guidance. 
The forms materials got fragmented into:
- some excellent pages about writing questions
- components that are not related to the above apart from a glancing discussion on this page: https://service-manual.nhs.uk/content/how-to-write-good-questions-for-forms/write-the-supporting-content-for-your-form that assumes that you know how to choose the appropriate component for type of form. We never did anything systematic about interaction design for forms
- the task list pattern which is somewhat about forms but isn't linked so far as I know to either of the points above.

When we did the original research on topics, we understood that we needed to have overarching topics as well as the details. That background seems to have got lost somewhere or ended up as this neglected issue.

I accept that I'm not part of setting current priorities, but that's a different matter to saying "this important thing is a closed item that we never need to think about again".

**Comment by sarawilcox** [comment] 2022-01-10 14:51
I agree, @cjforms. 

@georginaplatt, for info. There is a section on forms guidance in NHS.UK Confluence (https://nhsd-confluence.digital.nhs.uk/display/SMDS/Forms+guidance). We identified that good form design covers:

- interaction design - making the form easy to use (patterns and components)
- content design - making it easy to understand and answer (questions and other content)
- service design - making it easy for the user to get things done (process) 

But we only ever addressed the 2nd of these. 

One option might be to open an issue for interaction design for forms in the design system backlog. I don't see it being addressed in the near future but it could remain open there for further comment and input pending future priorisation exercises. What do you think, @cjforms?

**Comment by sarawilcox** [comment] 2022-01-10 16:56
I've set up an issue, @cjforms: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/410. Please feel free to add to it.

**Comment by baracoffice** [comment] 2022-05-04 10:42
Regarding @cjforms comment about the status "looking like a button" - I'm exploring having both the link and the status clickable - as a way in to the form. 
I am concerned that in some other settings, clicking on a "tag" would bring you to a collection of items using that tag, and that the pattern for the status elements is the same as that for tags. 
However, It might be that the affordance is strongly enough contextualised, so that in the task list it's clear that one can click and proceed, whereas in a "tag" setting, eg a search interface, it would be clear that clicking on a tag would give you all items tagged with that word. Also, the addition of a # to the word or phrase might be enough of a differentiator
