### ISSUE TITLE
EPIC: Refactor list panel component

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-service-manual#885] opened 2021-01-12 14:50 UTC
## What

Refactor the list panel component that exists in the NHS.UK frontend library 

## Why

The component is rarely used and is very similar to other components in the library, so the list panel component can be refactored into one of those reducing the number of components we have.

**Comment by AdamChrimes** [comment] 2021-04-21 13:34
I think this is something we need to look at in the near future, discuss at this weeks planning.

**Comment by CatherineReader** [comment] 2021-09-30 13:21
Duplicate of #1186  so I'm closing this ticket

**Closed by CatherineReader** 2021-09-30 13:21 UTC
Labels: epic, Theme: Design system
