### ISSUE TITLE
Review accessibility audits

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#917] opened 2021-01-28 10:52 UTC
## What

Review all accessibility audits, including the most recent Nomensa audit.

## Why

To identify any trends and patterns in the audits that might offer insight into valuable updates and guidance we can include in our accessibility guidance.

## Tasks

- [x] Review audits
- [x] Summarise any trends and patterns

**Comment by AJSMITH1512** [comment] 2021-02-05 09:24
Meeting set up with Michael Cheung to discuss the present reviews that have been undertaken and how this might be more formal process to ensure feeds through to Service Manual. If Reviews are being undertaken ned to understand the scope of reviews and how we capture the learning. Single issues in GitHub may need to have some way of recording regularity of  issue being reported.

**Comment by AJSMITH1512** [comment] 2021-02-08 14:39
Meeting undertaken:  

Audits are reviewed by Michael on request.

There is no central register of audits held they are all held by separate programmes on confluence or any other  repository.

Process review, provide advice if issue specific to the application/report.

If issue has been caused by use of the front-end library an issue is raised in Github and normally fixed in the next release of the front end-library.

If an issue has already ben raised no impact on Github - there is presently no way of recording that the issue has occurred on number of occasions other than through comments. Nota  real issue for front-end library given note above but for wider issues worth understanding how we might capture the fact tat the issue is being seen in multiple sites.

Michael has provided all the audits he has had recently to Alistair who has been through to provide ideas for areas to cover.

Given the above actions no further activity is seen as useful at this time.

**Closed by AJSMITH1512** 2021-02-08 14:39 UTC
Labels: :clock10: days, accessibility
