### ISSUE TITLE
Celebrate contributors

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#735] opened 2020-10-20 08:44 UTC
## What

Research and implement a way to celebrate contributors.

## Why

To recognise the time and effort contributors put into a contribution

## Tasks

- [ ] Research appropriate ways to celebrate contributors
- [ ] Implement changes

**Comment by AdamChrimes** [comment] 2021-03-23 11:35
Looks like a duplicate of https://github.com/nhsuk/nhsuk-service-manual/issues/1006

**Closed by AdamChrimes** 2021-03-23 11:35 UTC
